select
    wiser_id,
    hire_date,
    termination_date,
    employee_type,
    office,
    holiday_calendar_code,
    holiday_calendar_configured,
    management_level,
    team,
    sub_team,
    squad,
    cross_office_squad_status,
    job_family_group,
    job_family,
    role_productivity_category,
    is_technology_role,
    is_engineering_role,
    is_engineering_productivity_population,
    is_terminated,
    employment_status,
    cohort_month,
    substr(cohort_month, 1, 4) as cohort_year,
    is_true_onboarding_metric,
    in_reliability_window,
    first_pr_id,
    first_pr_merged_at,
    days_to_first_pr,
    business_days_to_first_pr,
    days_to_first_tier_3_pr,
    first_pr_repository_name,
    first_peer_velocity_match_ramp_month,
    first_90_day_median_cycle_time_days,
    office_nearest_hire_gap_days,
    office_other_hires_within_30_days,
    squad_nearest_hire_gap_days,
    squad_other_hires_within_30_days,
    days_since_hire,
    business_days_since_hire
from fct_employee_onboarding_summary
where role_productivity_category in ('Software Engineering', 'Technical Adjacent')
order by employee_type, office, management_level, squad, cohort_month
